spring.application.name=paging
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.servlet.expose-session-attributes=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:paging;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=false
